# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='A default title', max_length=30, verbose_name='\u6807\u9898')),
                ('Content', models.TextField(default='A default content', max_length=5000, verbose_name='\u5185\u5bb9')),
                ('Like', models.IntegerField(default=0, verbose_name='\u8d5e')),
                ('Pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('Revise_date', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u8ba2')),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(choices=[('M', '\u7537'), ('FM', '\u5973'), ('D', '\u9ed8\u8ba4')], default='D', max_length=2, verbose_name='\u6027\u522b')),
                ('Age', models.CharField(choices=[('B', '\u7ae5\u5e74'), ('K', '\u5e7c\u5e74'), ('S', '\u5c11\u5e74'), ('T', '\u9752\u5e74'), ('Y', '\u58ee\u5e74'), ('P', '\u4e2d\u5e74'), ('O', '\u8001\u725b'), ('D', '\u9ed8\u8ba4')], default='D', max_length=2, verbose_name='\u5e74\u7eaa')),
                ('Register_date', models.DateField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('Intro', models.TextField(default='Default intro', help_text='Introduce yourself.', max_length=500, verbose_name='\u81ea\u6211\u4ecb\u7ecd')),
                ('Followed', models.ManyToManyField(related_name='Followers', to='myblog.Blogger')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=10, verbose_name='\u8bc4\u8bba\u4eba')),
                ('Content', models.TextField(max_length=500, verbose_name='\u8bc4\u8bba')),
                ('Pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=30, verbose_name='\u6807\u7b7e')),
                ('Article', models.ManyToManyField(to='myblog.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Blogger'),
        ),
    ]
