# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='commenter',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
