# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
