# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20161027_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Blogger'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='Pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added date'),
        ),
    ]
