# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20161109_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Deleted',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u5220\u9664'),
        ),
    ]
