# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_article_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Deleted',
        ),
        migrations.AddField(
            model_name='article',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='\u72b6\u6001'),
        ),
    ]
