# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20161027_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='Author',
            field=models.CharField(max_length=10),
        ),
    ]
