# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20161027_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='Age',
            field=models.CharField(choices=[('Babe', 'Babe'), ('Kid', 'Kid'), ('Schoolchild', 'Schoolchild'), ('Teenage', 'Teenage'), ('Youth', 'Youth'), ('Postadolescent', 'Postadolescent'), ('Old', 'Old')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
