# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20161109_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='\u6fc0\u6d3b'),
        ),
    ]
