# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20161027_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('FM', 'Female')], max_length=20),
        ),
    ]
