# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 06:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_blogger_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blogger',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='commenter',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
