# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20161028_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='Age',
            field=models.CharField(choices=[('B', 'Babe'), ('K', 'Kid'), ('S', 'Schoolchild'), ('T', 'Teenage'), ('Y', 'Youth'), ('P', 'Postadolescent'), ('O', 'Old')], max_length=2),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('FM', 'Female')], max_length=2),
        ),
    ]
