# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20161110_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenter',
            name='Status',
            field=models.BooleanField(default=False, verbose_name='\u5c55\u793a'),
        ),
    ]
