# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20161028_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='Intro',
            field=models.CharField(help_text='Introduce yourself in 500 words.', max_length=500),
        ),
    ]
