# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_commenter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='\u5c55\u793a'),
        ),
    ]
