# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20161028_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='Intro',
            field=models.TextField(help_text='Introduce yourself in 500 words.', max_length=500),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='Content',
            field=models.TextField(max_length=500),
        ),
    ]
