# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20161028_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
