# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20161110_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='Nickname',
            field=models.CharField(default='AAA', max_length=30, verbose_name='\u6635\u79f0'),
        ),
    ]
