# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_blogger_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='Favicon',
            field=models.ImageField(default='static/myblog/image/default.jpg', null=True, upload_to='img/favicon'),
        ),
    ]
