# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Like',
            field=models.IntegerField(default=0),
        ),
    ]
