# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_blogger_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='Favicon',
            field=models.ImageField(default='../static/myblog/image/default.jpg', null=True, upload_to='img/favicon'),
        ),
    ]
