# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_auto_20161118_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Original_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to='myblog.Blogger'),
        ),
    ]
