# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20161123_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Original_id',
            field=models.IntegerField(null=True),
        ),
    ]
